# Site settings
title: Thiago Tomasi - UX/UI Designer and Front-end Engineer
author: Thiago Tomasi
author_title: UX/UI Designer and Front-end Engineer
email: alpaca.thiago@gmail.com
baseurl: ""
url: "http://www.thiagotomasi.com/"
twitter_username:  thiagotomasi
github_username:   thiagotomasi
facebook_username: thiagotomasi
medium_username:   thiagotomasi
linkedin_username: thiagotomasi

# Build settings
markdown: kramdown


exclude: [
  "gulpfile.js",
  "node_modules",
  "package.json"
]